[package]
name = "papa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
directories = "4.0.1"
futures-util = "0.3.21"
indicatif = "0.16.2"
regex = "1.5.6"
reqwest = { version = "0.11.10", features = ["stream"] }
tokio = { version = "1.18.2", features = ["full"] }
zip = "0.6.2"
